### ISSUE TITLE
兄嘚

### ISSUE THREAD

**Issue by changecj** [zhezhong17/yii2-migration#1]
composer require insolita/yii2-migration-generator

**Comment by zhezhong17** [comment]
...  正在开发中，没上线呢。 (第一次制作packagist)    你去用这个e282486518/yii2-console-migration  (我这个是参考它写的，然后改进一些问题，当作一个新的旅程开始把)

**Comment by zhezhong17** [comment]
已经开发完成上线了    如果你对它们的包还原度不满意的话可以试试我

**Comment by changecj** [comment]
> 已经开发完成上线了 如果你对它们的包还原度不满意的话可以试试我

最近在找这种包试试玩，结果找到并且达到了我的要求，但是感觉没啥用，因为对比起来，我自己写migration文件比在navicat上手动建表要简单些，敲代码第一次战胜了可视化工具的感觉。

不过用作备份或者新库完全没有migration的时候，非常好用，看使用场景吧，反正这种包我收藏了，后面用到的时候再说吧
